export const  ADD_TO_CART   ="ADD_TO_CART"
export const ADD_TO_CART_FAIL='ADD_TO_CART_FAIL'


export const GET_CART_ITEMS='GET_CART_ITEMS'
export const SAVE_SHIPPING_INFO='SAVE_SHIPPING_INFO'
export const GET_SHIPPING_INFO ='GET_SHIPPING_INFO'
export const REMOVE_TO_CART='REMOVE_TO_CART'
