export const  CRATE_ORDER_SUCCESS="CRATE_ORDER_SUCCESS"
export const  CRATE_ORDER_REQUEST="CRATE_ORDER_REQUEST"
export const CRATE_ORDER_FAIL="CRATE_ORDER_FAIL"

export const  GET_ORDER_SUCCESS="GET_ ORDER_SUCCESS"
export const  GET_ORDER_REQUEST="GET_ORDER_REQUEST"
export const GET_ORDER_FAIL="GET_ORDER_FAIL"

export const  ORDER_DETAIL_SUCCESS="ORDER_DETAIL_SUCCESS"
export const  ORDER_DETAIL_REQUEST="ORDER_DETAIL_REQUEST"
export const ORDER_DETAIL_FAIL="ORDER_DETAIL_FAIL"


export const CLEAR_ERROR ="CLEAR_ERROR"